# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FBalgC <- function(y2, m, delta, pr, Mx, Mx2, gamma, d, S, S2) {
    .Call('BayesHSMMcat_FBalgC', PACKAGE = 'BayesHSMMcat', y2, m, delta, pr, Mx, Mx2, gamma, d, S, S2)
}

