# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
FBalgC <- function(y2, m, delta, pr, Mx, Mx2, gamma, d, S, S2) {
    .Call('_medHMM_FBalgC', PACKAGE = 'medHMM', y2, m, delta, pr, Mx, Mx2, gamma, d, S, S2)
}

#' @keywords internal
FBalgCF <- function(y2, m, delta, pr, Mx, Mx2, gamma, d, S, S2, S3) {
    .Call('_medHMM_FBalgCF', PACKAGE = 'medHMM', y2, m, delta, pr, Mx, Mx2, gamma, d, S, S2, S3)
}

