# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
FBalgC <- function(y2, m, delta, pr, Mx, Mx2, gamma, d, S, S2) {
    .Call(`_medHMM_FBalgC`, y2, m, delta, pr, Mx, Mx2, gamma, d, S, S2)
}

#' @keywords internal
FBalgCF <- function(y2, m, delta, pr, Mx, Mx2, gamma, d, S, S2, S3) {
    .Call(`_medHMM_FBalgCF`, y2, m, delta, pr, Mx, Mx2, gamma, d, S, S2, S3)
}

#' @keywords internal
mult_ed_fb_cpp <- function(m, n, delta, allprobs, Mx, Mx2, gamma, d, S, S2) {
    .Call(`_medHMM_mult_ed_fb_cpp`, m, n, delta, allprobs, Mx, Mx2, gamma, d, S, S2)
}

